#!/bin/bash

echo "🔄 FORCING BROWSER CACHE CLEAR"
echo "=============================="
echo ""
echo "The token is still showing as false because your browser"
echo "might be using cached JavaScript files."
echo ""
echo "⚡ DO THIS NOW:"
echo ""
echo "1. In your browser (http://localhost:3000):"
echo "   - Press Cmd+Shift+R (Mac) or Ctrl+Shift+R (Windows)"
echo "   - This does a HARD REFRESH and clears cache"
echo ""
echo "2. OR use this JavaScript in console:"
echo ""
echo "   localStorage.clear();"
echo "   sessionStorage.clear();"
echo "   location.reload(true);"
echo ""
echo "3. THEN check if you see this in console:"
echo "   🔑 Token exists: true"
echo "   🔑 Token from: Supabase session"
echo ""
echo "=============================="
echo ""
echo "If token is STILL false after hard refresh:"
echo "  -> You need to LOG IN at http://localhost:3000/login"
echo "  -> The Supabase session doesn't exist yet"
echo ""
